# This files contains your custom actions which can be used to run
# custom Python code.
#
# See this guide on how to implement these action:
# https://rasa.com/docs/rasa/custom-actions


# This is a simple example for a custom action which utters "Hello World!"

from typing import Any, Text, Dict, List
from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
import requests

class ActionCheckShipment(Action):
    def name(self) -> Text:
        return "action_check_shipment"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
        tracking_number = tracker.get_slot("tracking_number")
        
        # Here you would typically make an API call to your shipping system
        # For demo purposes, we'll return a mock response
        
        # Detect language based on the user's input
        last_message = tracker.latest_message.get("text", "")
        is_arabic = any("\u0600" <= char <= "\u06FF" for char in last_message)
        
        if is_arabic:
            response = f"شحنتك رقم {tracking_number} في الطريق إليك وستصل خلال 2-3 أيام."
        else:
            response = f"Your shipment {tracking_number} is on its way and will be delivered in 2-3 days."
            
        dispatcher.utter_message(text=response)
        return []

class ActionCreateTicket(Action):
    def name(self) -> Text:
        return "action_create_ticket"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
        tracking_number = tracker.get_slot("tracking_number")
        
        # Here you would typically create a ticket in your support system
        # For demo purposes, we'll just acknowledge the ticket creation
        
        # Detect language based on the user's input
        last_message = tracker.latest_message.get("text", "")
        is_arabic = any("\u0600" <= char <= "\u06FF" for char in last_message)
        
        if is_arabic:
            ticket_number = "12345"  # This would be generated by your ticketing system
            response = f"تم إنشاء تذكرة دعم رقم {ticket_number} لشحنتك {tracking_number}."
        else:
            ticket_number = "12345"  # This would be generated by your ticketing system
            response = f"Support ticket #{ticket_number} has been created for your shipment {tracking_number}."
            
        dispatcher.utter_message(text=response)
        return []

# from typing import Any, Text, Dict, List
#
# from rasa_sdk import Action, Tracker
# from rasa_sdk.executor import CollectingDispatcher
#
#
# class ActionHelloWorld(Action):
#
#     def name(self) -> Text:
#         return "action_hello_world"
#
#     def run(self, dispatcher: CollectingDispatcher,
#             tracker: Tracker,
#             domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
#
#         dispatcher.utter_message(text="Hello World!")
#
#         return []
