name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd backend && npm install
      - run: cd backend && npm run lint || true
      - run: cd backend && npm test || true
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  build-rasa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rasa:latest ./rasa
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rasa:latest 