name: Rasa CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'rasa/**'
      - '.github/workflows/rasa.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'rasa/**'
      - '.github/workflows/rasa.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: rasa/requirements.txt
    
    - name: Install dependencies
      working-directory: ./rasa
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8
    
    - name: Run linting
      working-directory: ./rasa
      run: flake8 .
    
    - name: Run tests
      working-directory: ./rasa
      run: |
        rasa test nlu --nlu data/nlu.yml
        rasa test core --stories data/stories.yml
    
    - name: Build Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker build -t ${{ github.repository }}/rasa:${{ github.sha }} -f rasa/Dockerfile ./rasa
    
    - name: Login to GitHub Container Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker tag ${{ github.repository }}/rasa:${{ github.sha }} ghcr.io/${{ github.repository }}/rasa:${{ github.sha }}
        docker tag ${{ github.repository }}/rasa:${{ github.sha }} ghcr.io/${{ github.repository }}/rasa:latest
        docker push ghcr.io/${{ github.repository }}/rasa:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/rasa:latest 